export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const BAD_REQUEST = "BAD_REQUEST";
export const UNAUTHORIZED = "UNAUTHORIZED";

//User api
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const DUPLICATE_USER_FOUND = "DUPLICATE_USER_FOUND";
